#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UVirtualClass.DataContext
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PortalEdu")]
	public partial class ContextDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertcompras(compras instance);
    partial void Updatecompras(compras instance);
    partial void Deletecompras(compras instance);
    partial void InsertAlumno(Alumno instance);
    partial void UpdateAlumno(Alumno instance);
    partial void DeleteAlumno(Alumno instance);
    partial void InsertCursoAlumno(CursoAlumno instance);
    partial void UpdateCursoAlumno(CursoAlumno instance);
    partial void DeleteCursoAlumno(CursoAlumno instance);
    partial void InsertCursos(Cursos instance);
    partial void UpdateCursos(Cursos instance);
    partial void DeleteCursos(Cursos instance);
    partial void Insertdetallecompra(detallecompra instance);
    partial void Updatedetallecompra(detallecompra instance);
    partial void Deletedetallecompra(detallecompra instance);
    partial void InsertDocentes(Docentes instance);
    partial void UpdateDocentes(Docentes instance);
    partial void DeleteDocentes(Docentes instance);
    partial void InsertNotas(Notas instance);
    partial void UpdateNotas(Notas instance);
    partial void DeleteNotas(Notas instance);
    partial void InsertPagos(Pagos instance);
    partial void UpdatePagos(Pagos instance);
    partial void DeletePagos(Pagos instance);
    partial void InsertTemario(Temario instance);
    partial void UpdateTemario(Temario instance);
    partial void DeleteTemario(Temario instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    #endregion
		
		public ContextDbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PortalEduConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ContextDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContextDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContextDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContextDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<compras> compras
		{
			get
			{
				return this.GetTable<compras>();
			}
		}
		
		public System.Data.Linq.Table<Alumno> Alumno
		{
			get
			{
				return this.GetTable<Alumno>();
			}
		}
		
		public System.Data.Linq.Table<CursoAlumno> CursoAlumno
		{
			get
			{
				return this.GetTable<CursoAlumno>();
			}
		}
		
		public System.Data.Linq.Table<Cursos> Cursos
		{
			get
			{
				return this.GetTable<Cursos>();
			}
		}
		
		public System.Data.Linq.Table<detallecompra> detallecompra
		{
			get
			{
				return this.GetTable<detallecompra>();
			}
		}
		
		public System.Data.Linq.Table<Docentes> Docentes
		{
			get
			{
				return this.GetTable<Docentes>();
			}
		}
		
		public System.Data.Linq.Table<Notas> Notas
		{
			get
			{
				return this.GetTable<Notas>();
			}
		}
		
		public System.Data.Linq.Table<Pagos> Pagos
		{
			get
			{
				return this.GetTable<Pagos>();
			}
		}
		
		public System.Data.Linq.Table<Temario> Temario
		{
			get
			{
				return this.GetTable<Temario>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuario
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Inscripciones_del_Curso> Inscripciones_del_Curso
		{
			get
			{
				return this.GetTable<Inscripciones_del_Curso>();
			}
		}
		
		public System.Data.Linq.Table<ViewAlumnos> ViewAlumnos
		{
			get
			{
				return this.GetTable<ViewAlumnos>();
			}
		}
		
		public System.Data.Linq.Table<ViewCurso> ViewCurso
		{
			get
			{
				return this.GetTable<ViewCurso>();
			}
		}
		
		public System.Data.Linq.Table<ViewDocentes> ViewDocentes
		{
			get
			{
				return this.GetTable<ViewDocentes>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ModificaAlumno")]
		public ISingleResult<SP_ModificaAlumnoResult> SP_ModificaAlumno([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idAlumno, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fecha_n, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> genero)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idAlumno, nombre, apellido, fecha_n, genero);
			return ((ISingleResult<SP_ModificaAlumnoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ModificaCursos")]
		public ISingleResult<SP_ModificaCursosResult> SP_ModificaCursos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCurso, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(30)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(200)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Recursos", DbType="VarChar(30)")] string recursos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Costo", DbType="Money")] System.Nullable<decimal> costo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Foto", DbType="VarChar(MAX)")] string foto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCurso, nombre, descripcion, recursos, costo, foto);
			return ((ISingleResult<SP_ModificaCursosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ModificaDocente")]
		public ISingleResult<SP_ModificaDocenteResult> SP_ModificaDocente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idDocentes, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string apellido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fecha_n, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> genero, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Int")] System.Nullable<int> idUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idDocentes, nombre, apellido, fecha_n, genero, idUsuario);
			return ((ISingleResult<SP_ModificaDocenteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ModificaNotas")]
		public ISingleResult<SP_ModificaNotasResult> SP_ModificaNotas([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idNota, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nota", DbType="Decimal(18,0)")] System.Nullable<decimal> nota, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(15)")] string estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idNota, nota, estado);
			return ((ISingleResult<SP_ModificaNotasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ModificaTemarios")]
		public ISingleResult<SP_ModificaTemariosResult> SP_ModificaTemarios([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTema, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tema", DbType="VarChar(30)")] string tema, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(200)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTema, tema, descripcion);
			return ((ISingleResult<SP_ModificaTemariosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ModificaUsuario")]
		public ISingleResult<SP_ModificaUsuarioResult> SP_ModificaUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(60)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(60)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string contraseña, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Activo", DbType="Int")] System.Nullable<int> activo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tipo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, usuario, correo, contraseña, activo, tipo);
			return ((ISingleResult<SP_ModificaUsuarioResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.compras")]
	public partial class compras : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_Compra;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private System.Nullable<decimal> _valorcompra;
		
		private string _tipotc;
		
		private string _nombretc;
		
		private string _bancotc;
		
		private string _numerotc;
		
		private System.Nullable<int> _ccv;
		
		private System.Nullable<int> _mestc;
		
		private System.Nullable<int> _aniotc;
		
		private System.Nullable<int> _IdUsuario;
		
		private EntitySet<detallecompra> _detallecompra;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_CompraChanging(int value);
    partial void Onid_CompraChanged();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void OnvalorcompraChanging(System.Nullable<decimal> value);
    partial void OnvalorcompraChanged();
    partial void OntipotcChanging(string value);
    partial void OntipotcChanged();
    partial void OnnombretcChanging(string value);
    partial void OnnombretcChanged();
    partial void OnbancotcChanging(string value);
    partial void OnbancotcChanged();
    partial void OnnumerotcChanging(string value);
    partial void OnnumerotcChanged();
    partial void OnccvChanging(System.Nullable<int> value);
    partial void OnccvChanged();
    partial void OnmestcChanging(System.Nullable<int> value);
    partial void OnmestcChanged();
    partial void OnaniotcChanging(System.Nullable<int> value);
    partial void OnaniotcChanged();
    partial void OnIdUsuarioChanging(System.Nullable<int> value);
    partial void OnIdUsuarioChanged();
    #endregion
		
		public compras()
		{
			this._detallecompra = new EntitySet<detallecompra>(new Action<detallecompra>(this.attach_detallecompra), new Action<detallecompra>(this.detach_detallecompra));
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Compra", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_Compra
		{
			get
			{
				return this._id_Compra;
			}
			set
			{
				if ((this._id_Compra != value))
				{
					this.Onid_CompraChanging(value);
					this.SendPropertyChanging();
					this._id_Compra = value;
					this.SendPropertyChanged("id_Compra");
					this.Onid_CompraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valorcompra", DbType="Money")]
		public System.Nullable<decimal> valorcompra
		{
			get
			{
				return this._valorcompra;
			}
			set
			{
				if ((this._valorcompra != value))
				{
					this.OnvalorcompraChanging(value);
					this.SendPropertyChanging();
					this._valorcompra = value;
					this.SendPropertyChanged("valorcompra");
					this.OnvalorcompraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipotc", DbType="VarChar(25)")]
		public string tipotc
		{
			get
			{
				return this._tipotc;
			}
			set
			{
				if ((this._tipotc != value))
				{
					this.OntipotcChanging(value);
					this.SendPropertyChanging();
					this._tipotc = value;
					this.SendPropertyChanged("tipotc");
					this.OntipotcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombretc", DbType="VarChar(50)")]
		public string nombretc
		{
			get
			{
				return this._nombretc;
			}
			set
			{
				if ((this._nombretc != value))
				{
					this.OnnombretcChanging(value);
					this.SendPropertyChanging();
					this._nombretc = value;
					this.SendPropertyChanged("nombretc");
					this.OnnombretcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bancotc", DbType="VarChar(50)")]
		public string bancotc
		{
			get
			{
				return this._bancotc;
			}
			set
			{
				if ((this._bancotc != value))
				{
					this.OnbancotcChanging(value);
					this.SendPropertyChanging();
					this._bancotc = value;
					this.SendPropertyChanged("bancotc");
					this.OnbancotcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numerotc", DbType="VarChar(50)")]
		public string numerotc
		{
			get
			{
				return this._numerotc;
			}
			set
			{
				if ((this._numerotc != value))
				{
					this.OnnumerotcChanging(value);
					this.SendPropertyChanging();
					this._numerotc = value;
					this.SendPropertyChanged("numerotc");
					this.OnnumerotcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccv", DbType="Int")]
		public System.Nullable<int> ccv
		{
			get
			{
				return this._ccv;
			}
			set
			{
				if ((this._ccv != value))
				{
					this.OnccvChanging(value);
					this.SendPropertyChanging();
					this._ccv = value;
					this.SendPropertyChanged("ccv");
					this.OnccvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mestc", DbType="Int")]
		public System.Nullable<int> mestc
		{
			get
			{
				return this._mestc;
			}
			set
			{
				if ((this._mestc != value))
				{
					this.OnmestcChanging(value);
					this.SendPropertyChanging();
					this._mestc = value;
					this.SendPropertyChanged("mestc");
					this.OnmestcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aniotc", DbType="Int")]
		public System.Nullable<int> aniotc
		{
			get
			{
				return this._aniotc;
			}
			set
			{
				if ((this._aniotc != value))
				{
					this.OnaniotcChanging(value);
					this.SendPropertyChanging();
					this._aniotc = value;
					this.SendPropertyChanged("aniotc");
					this.OnaniotcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int")]
		public System.Nullable<int> IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="compras_detallecompra", Storage="_detallecompra", ThisKey="id_Compra", OtherKey="idcompradetalle")]
		public EntitySet<detallecompra> detallecompra
		{
			get
			{
				return this._detallecompra;
			}
			set
			{
				this._detallecompra.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_compras", Storage="_Usuario", ThisKey="IdUsuario", OtherKey="IdUsuario", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.compras.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.compras.Add(this);
						this._IdUsuario = value.IdUsuario;
					}
					else
					{
						this._IdUsuario = default(Nullable<int>);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detallecompra(detallecompra entity)
		{
			this.SendPropertyChanging();
			entity.compras = this;
		}
		
		private void detach_detallecompra(detallecompra entity)
		{
			this.SendPropertyChanging();
			entity.compras = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Alumno")]
	public partial class Alumno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdAlumno;
		
		private string _nombre;
		
		private string _apellido;
		
		private System.Nullable<System.DateTime> _fecha_n;
		
		private System.Nullable<char> _genero;
		
		private System.Nullable<int> _idUsuario;
		
		private EntitySet<CursoAlumno> _CursoAlumno;
		
		private EntitySet<Pagos> _Pagos;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdAlumnoChanging(int value);
    partial void OnIdAlumnoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void Onfecha_nChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_nChanged();
    partial void OngeneroChanging(System.Nullable<char> value);
    partial void OngeneroChanged();
    partial void OnidUsuarioChanging(System.Nullable<int> value);
    partial void OnidUsuarioChanged();
    #endregion
		
		public Alumno()
		{
			this._CursoAlumno = new EntitySet<CursoAlumno>(new Action<CursoAlumno>(this.attach_CursoAlumno), new Action<CursoAlumno>(this.detach_CursoAlumno));
			this._Pagos = new EntitySet<Pagos>(new Action<Pagos>(this.attach_Pagos), new Action<Pagos>(this.detach_Pagos));
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAlumno", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdAlumno
		{
			get
			{
				return this._IdAlumno;
			}
			set
			{
				if ((this._IdAlumno != value))
				{
					this.OnIdAlumnoChanging(value);
					this.SendPropertyChanging();
					this._IdAlumno = value;
					this.SendPropertyChanged("IdAlumno");
					this.OnIdAlumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(30)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(30)")]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_n", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_n
		{
			get
			{
				return this._fecha_n;
			}
			set
			{
				if ((this._fecha_n != value))
				{
					this.Onfecha_nChanging(value);
					this.SendPropertyChanging();
					this._fecha_n = value;
					this.SendPropertyChanged("fecha_n");
					this.Onfecha_nChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genero", DbType="Char(1)")]
		public System.Nullable<char> genero
		{
			get
			{
				return this._genero;
			}
			set
			{
				if ((this._genero != value))
				{
					this.OngeneroChanging(value);
					this.SendPropertyChanging();
					this._genero = value;
					this.SendPropertyChanged("genero");
					this.OngeneroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int")]
		public System.Nullable<int> idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Alumno_CursoAlumno", Storage="_CursoAlumno", ThisKey="IdAlumno", OtherKey="IdAlumno")]
		public EntitySet<CursoAlumno> CursoAlumno
		{
			get
			{
				return this._CursoAlumno;
			}
			set
			{
				this._CursoAlumno.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Alumno_Pagos", Storage="_Pagos", ThisKey="IdAlumno", OtherKey="IdAlumno")]
		public EntitySet<Pagos> Pagos
		{
			get
			{
				return this._Pagos;
			}
			set
			{
				this._Pagos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Alumno", Storage="_Usuario", ThisKey="idUsuario", OtherKey="IdUsuario", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Alumno.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Alumno.Add(this);
						this._idUsuario = value.IdUsuario;
					}
					else
					{
						this._idUsuario = default(Nullable<int>);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CursoAlumno(CursoAlumno entity)
		{
			this.SendPropertyChanging();
			entity.Alumno = this;
		}
		
		private void detach_CursoAlumno(CursoAlumno entity)
		{
			this.SendPropertyChanging();
			entity.Alumno = null;
		}
		
		private void attach_Pagos(Pagos entity)
		{
			this.SendPropertyChanging();
			entity.Alumno = this;
		}
		
		private void detach_Pagos(Pagos entity)
		{
			this.SendPropertyChanging();
			entity.Alumno = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CursoAlumno")]
	public partial class CursoAlumno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdCurso_Alumno;
		
		private System.Nullable<int> _IdCurso;
		
		private System.Nullable<int> _IdAlumno;
		
		private EntitySet<Notas> _Notas;
		
		private EntityRef<Alumno> _Alumno;
		
		private EntityRef<Cursos> _Cursos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCurso_AlumnoChanging(int value);
    partial void OnIdCurso_AlumnoChanged();
    partial void OnIdCursoChanging(System.Nullable<int> value);
    partial void OnIdCursoChanged();
    partial void OnIdAlumnoChanging(System.Nullable<int> value);
    partial void OnIdAlumnoChanged();
    #endregion
		
		public CursoAlumno()
		{
			this._Notas = new EntitySet<Notas>(new Action<Notas>(this.attach_Notas), new Action<Notas>(this.detach_Notas));
			this._Alumno = default(EntityRef<Alumno>);
			this._Cursos = default(EntityRef<Cursos>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCurso_Alumno", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdCurso_Alumno
		{
			get
			{
				return this._IdCurso_Alumno;
			}
			set
			{
				if ((this._IdCurso_Alumno != value))
				{
					this.OnIdCurso_AlumnoChanging(value);
					this.SendPropertyChanging();
					this._IdCurso_Alumno = value;
					this.SendPropertyChanged("IdCurso_Alumno");
					this.OnIdCurso_AlumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCurso", DbType="Int")]
		public System.Nullable<int> IdCurso
		{
			get
			{
				return this._IdCurso;
			}
			set
			{
				if ((this._IdCurso != value))
				{
					if (this._Cursos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCursoChanging(value);
					this.SendPropertyChanging();
					this._IdCurso = value;
					this.SendPropertyChanged("IdCurso");
					this.OnIdCursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAlumno", DbType="Int")]
		public System.Nullable<int> IdAlumno
		{
			get
			{
				return this._IdAlumno;
			}
			set
			{
				if ((this._IdAlumno != value))
				{
					if (this._Alumno.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdAlumnoChanging(value);
					this.SendPropertyChanging();
					this._IdAlumno = value;
					this.SendPropertyChanged("IdAlumno");
					this.OnIdAlumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CursoAlumno_Notas", Storage="_Notas", ThisKey="IdCurso_Alumno", OtherKey="idCursoAlumno")]
		public EntitySet<Notas> Notas
		{
			get
			{
				return this._Notas;
			}
			set
			{
				this._Notas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Alumno_CursoAlumno", Storage="_Alumno", ThisKey="IdAlumno", OtherKey="IdAlumno", IsForeignKey=true)]
		public Alumno Alumno
		{
			get
			{
				return this._Alumno.Entity;
			}
			set
			{
				Alumno previousValue = this._Alumno.Entity;
				if (((previousValue != value) 
							|| (this._Alumno.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Alumno.Entity = null;
						previousValue.CursoAlumno.Remove(this);
					}
					this._Alumno.Entity = value;
					if ((value != null))
					{
						value.CursoAlumno.Add(this);
						this._IdAlumno = value.IdAlumno;
					}
					else
					{
						this._IdAlumno = default(Nullable<int>);
					}
					this.SendPropertyChanged("Alumno");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cursos_CursoAlumno", Storage="_Cursos", ThisKey="IdCurso", OtherKey="IdCurso", IsForeignKey=true)]
		public Cursos Cursos
		{
			get
			{
				return this._Cursos.Entity;
			}
			set
			{
				Cursos previousValue = this._Cursos.Entity;
				if (((previousValue != value) 
							|| (this._Cursos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cursos.Entity = null;
						previousValue.CursoAlumno.Remove(this);
					}
					this._Cursos.Entity = value;
					if ((value != null))
					{
						value.CursoAlumno.Add(this);
						this._IdCurso = value.IdCurso;
					}
					else
					{
						this._IdCurso = default(Nullable<int>);
					}
					this.SendPropertyChanged("Cursos");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Notas(Notas entity)
		{
			this.SendPropertyChanging();
			entity.CursoAlumno = this;
		}
		
		private void detach_Notas(Notas entity)
		{
			this.SendPropertyChanging();
			entity.CursoAlumno = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cursos")]
	public partial class Cursos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdCurso;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		private string _Recursos;
		
		private System.Nullable<decimal> _Costo;
		
		private System.Nullable<int> _idDocente;
		
		private string _Foto;
		
		private string _Videointro;
		
		private EntitySet<CursoAlumno> _CursoAlumno;
		
		private EntitySet<detallecompra> _detallecompra;
		
		private EntitySet<Pagos> _Pagos;
		
		private EntitySet<Temario> _Temario;
		
		private EntityRef<Docentes> _Docentes;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCursoChanging(int value);
    partial void OnIdCursoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnRecursosChanging(string value);
    partial void OnRecursosChanged();
    partial void OnCostoChanging(System.Nullable<decimal> value);
    partial void OnCostoChanged();
    partial void OnidDocenteChanging(System.Nullable<int> value);
    partial void OnidDocenteChanged();
    partial void OnFotoChanging(string value);
    partial void OnFotoChanged();
    partial void OnVideointroChanging(string value);
    partial void OnVideointroChanged();
    #endregion
		
		public Cursos()
		{
			this._CursoAlumno = new EntitySet<CursoAlumno>(new Action<CursoAlumno>(this.attach_CursoAlumno), new Action<CursoAlumno>(this.detach_CursoAlumno));
			this._detallecompra = new EntitySet<detallecompra>(new Action<detallecompra>(this.attach_detallecompra), new Action<detallecompra>(this.detach_detallecompra));
			this._Pagos = new EntitySet<Pagos>(new Action<Pagos>(this.attach_Pagos), new Action<Pagos>(this.detach_Pagos));
			this._Temario = new EntitySet<Temario>(new Action<Temario>(this.attach_Temario), new Action<Temario>(this.detach_Temario));
			this._Docentes = default(EntityRef<Docentes>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCurso", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdCurso
		{
			get
			{
				return this._IdCurso;
			}
			set
			{
				if ((this._IdCurso != value))
				{
					this.OnIdCursoChanging(value);
					this.SendPropertyChanging();
					this._IdCurso = value;
					this.SendPropertyChanged("IdCurso");
					this.OnIdCursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(30)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(200)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recursos", DbType="VarChar(30)")]
		public string Recursos
		{
			get
			{
				return this._Recursos;
			}
			set
			{
				if ((this._Recursos != value))
				{
					this.OnRecursosChanging(value);
					this.SendPropertyChanging();
					this._Recursos = value;
					this.SendPropertyChanged("Recursos");
					this.OnRecursosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Costo", DbType="Money")]
		public System.Nullable<decimal> Costo
		{
			get
			{
				return this._Costo;
			}
			set
			{
				if ((this._Costo != value))
				{
					this.OnCostoChanging(value);
					this.SendPropertyChanging();
					this._Costo = value;
					this.SendPropertyChanged("Costo");
					this.OnCostoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDocente", DbType="Int")]
		public System.Nullable<int> idDocente
		{
			get
			{
				return this._idDocente;
			}
			set
			{
				if ((this._idDocente != value))
				{
					if (this._Docentes.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidDocenteChanging(value);
					this.SendPropertyChanging();
					this._idDocente = value;
					this.SendPropertyChanged("idDocente");
					this.OnidDocenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foto", DbType="VarChar(MAX)")]
		public string Foto
		{
			get
			{
				return this._Foto;
			}
			set
			{
				if ((this._Foto != value))
				{
					this.OnFotoChanging(value);
					this.SendPropertyChanging();
					this._Foto = value;
					this.SendPropertyChanged("Foto");
					this.OnFotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Videointro", DbType="VarChar(MAX)")]
		public string Videointro
		{
			get
			{
				return this._Videointro;
			}
			set
			{
				if ((this._Videointro != value))
				{
					this.OnVideointroChanging(value);
					this.SendPropertyChanging();
					this._Videointro = value;
					this.SendPropertyChanged("Videointro");
					this.OnVideointroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cursos_CursoAlumno", Storage="_CursoAlumno", ThisKey="IdCurso", OtherKey="IdCurso")]
		public EntitySet<CursoAlumno> CursoAlumno
		{
			get
			{
				return this._CursoAlumno;
			}
			set
			{
				this._CursoAlumno.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cursos_detallecompra", Storage="_detallecompra", ThisKey="IdCurso", OtherKey="idcursodetalle")]
		public EntitySet<detallecompra> detallecompra
		{
			get
			{
				return this._detallecompra;
			}
			set
			{
				this._detallecompra.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cursos_Pagos", Storage="_Pagos", ThisKey="IdCurso", OtherKey="IdCurso")]
		public EntitySet<Pagos> Pagos
		{
			get
			{
				return this._Pagos;
			}
			set
			{
				this._Pagos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cursos_Temario", Storage="_Temario", ThisKey="IdCurso", OtherKey="IdCurso")]
		public EntitySet<Temario> Temario
		{
			get
			{
				return this._Temario;
			}
			set
			{
				this._Temario.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Docentes_Cursos", Storage="_Docentes", ThisKey="idDocente", OtherKey="IdDocente", IsForeignKey=true)]
		public Docentes Docentes
		{
			get
			{
				return this._Docentes.Entity;
			}
			set
			{
				Docentes previousValue = this._Docentes.Entity;
				if (((previousValue != value) 
							|| (this._Docentes.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Docentes.Entity = null;
						previousValue.Cursos.Remove(this);
					}
					this._Docentes.Entity = value;
					if ((value != null))
					{
						value.Cursos.Add(this);
						this._idDocente = value.IdDocente;
					}
					else
					{
						this._idDocente = default(Nullable<int>);
					}
					this.SendPropertyChanged("Docentes");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CursoAlumno(CursoAlumno entity)
		{
			this.SendPropertyChanging();
			entity.Cursos = this;
		}
		
		private void detach_CursoAlumno(CursoAlumno entity)
		{
			this.SendPropertyChanging();
			entity.Cursos = null;
		}
		
		private void attach_detallecompra(detallecompra entity)
		{
			this.SendPropertyChanging();
			entity.Cursos = this;
		}
		
		private void detach_detallecompra(detallecompra entity)
		{
			this.SendPropertyChanging();
			entity.Cursos = null;
		}
		
		private void attach_Pagos(Pagos entity)
		{
			this.SendPropertyChanging();
			entity.Cursos = this;
		}
		
		private void detach_Pagos(Pagos entity)
		{
			this.SendPropertyChanging();
			entity.Cursos = null;
		}
		
		private void attach_Temario(Temario entity)
		{
			this.SendPropertyChanging();
			entity.Cursos = this;
		}
		
		private void detach_Temario(Temario entity)
		{
			this.SendPropertyChanging();
			entity.Cursos = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.detallecompra")]
	public partial class detallecompra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_detallecompra;
		
		private string _curso;
		
		private System.Nullable<decimal> _precio;
		
		private System.Nullable<int> _idcompradetalle;
		
		private System.Nullable<int> _idcursodetalle;
		
		private EntityRef<compras> _compras;
		
		private EntityRef<Cursos> _Cursos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_detallecompraChanging(int value);
    partial void Onid_detallecompraChanged();
    partial void OncursoChanging(string value);
    partial void OncursoChanged();
    partial void OnprecioChanging(System.Nullable<decimal> value);
    partial void OnprecioChanged();
    partial void OnidcompradetalleChanging(System.Nullable<int> value);
    partial void OnidcompradetalleChanged();
    partial void OnidcursodetalleChanging(System.Nullable<int> value);
    partial void OnidcursodetalleChanged();
    #endregion
		
		public detallecompra()
		{
			this._compras = default(EntityRef<compras>);
			this._Cursos = default(EntityRef<Cursos>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_detallecompra", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_detallecompra
		{
			get
			{
				return this._id_detallecompra;
			}
			set
			{
				if ((this._id_detallecompra != value))
				{
					this.Onid_detallecompraChanging(value);
					this.SendPropertyChanging();
					this._id_detallecompra = value;
					this.SendPropertyChanged("id_detallecompra");
					this.Onid_detallecompraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_curso", DbType="VarChar(60)")]
		public string curso
		{
			get
			{
				return this._curso;
			}
			set
			{
				if ((this._curso != value))
				{
					this.OncursoChanging(value);
					this.SendPropertyChanging();
					this._curso = value;
					this.SendPropertyChanged("curso");
					this.OncursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Money")]
		public System.Nullable<decimal> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcompradetalle", DbType="Int")]
		public System.Nullable<int> idcompradetalle
		{
			get
			{
				return this._idcompradetalle;
			}
			set
			{
				if ((this._idcompradetalle != value))
				{
					if (this._compras.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidcompradetalleChanging(value);
					this.SendPropertyChanging();
					this._idcompradetalle = value;
					this.SendPropertyChanged("idcompradetalle");
					this.OnidcompradetalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcursodetalle", DbType="Int")]
		public System.Nullable<int> idcursodetalle
		{
			get
			{
				return this._idcursodetalle;
			}
			set
			{
				if ((this._idcursodetalle != value))
				{
					if (this._Cursos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidcursodetalleChanging(value);
					this.SendPropertyChanging();
					this._idcursodetalle = value;
					this.SendPropertyChanged("idcursodetalle");
					this.OnidcursodetalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="compras_detallecompra", Storage="_compras", ThisKey="idcompradetalle", OtherKey="id_Compra", IsForeignKey=true)]
		public compras compras
		{
			get
			{
				return this._compras.Entity;
			}
			set
			{
				compras previousValue = this._compras.Entity;
				if (((previousValue != value) 
							|| (this._compras.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._compras.Entity = null;
						previousValue.detallecompra.Remove(this);
					}
					this._compras.Entity = value;
					if ((value != null))
					{
						value.detallecompra.Add(this);
						this._idcompradetalle = value.id_Compra;
					}
					else
					{
						this._idcompradetalle = default(Nullable<int>);
					}
					this.SendPropertyChanged("compras");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cursos_detallecompra", Storage="_Cursos", ThisKey="idcursodetalle", OtherKey="IdCurso", IsForeignKey=true)]
		public Cursos Cursos
		{
			get
			{
				return this._Cursos.Entity;
			}
			set
			{
				Cursos previousValue = this._Cursos.Entity;
				if (((previousValue != value) 
							|| (this._Cursos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cursos.Entity = null;
						previousValue.detallecompra.Remove(this);
					}
					this._Cursos.Entity = value;
					if ((value != null))
					{
						value.detallecompra.Add(this);
						this._idcursodetalle = value.IdCurso;
					}
					else
					{
						this._idcursodetalle = default(Nullable<int>);
					}
					this.SendPropertyChanged("Cursos");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Docentes")]
	public partial class Docentes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdDocente;
		
		private string _nombre;
		
		private string _apellido;
		
		private System.Nullable<System.DateTime> _fecha_n;
		
		private System.Nullable<char> _genero;
		
		private System.Nullable<int> _idUsuario;
		
		private EntitySet<Cursos> _Cursos;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdDocenteChanging(int value);
    partial void OnIdDocenteChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void Onfecha_nChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_nChanged();
    partial void OngeneroChanging(System.Nullable<char> value);
    partial void OngeneroChanged();
    partial void OnidUsuarioChanging(System.Nullable<int> value);
    partial void OnidUsuarioChanged();
    #endregion
		
		public Docentes()
		{
			this._Cursos = new EntitySet<Cursos>(new Action<Cursos>(this.attach_Cursos), new Action<Cursos>(this.detach_Cursos));
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDocente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdDocente
		{
			get
			{
				return this._IdDocente;
			}
			set
			{
				if ((this._IdDocente != value))
				{
					this.OnIdDocenteChanging(value);
					this.SendPropertyChanging();
					this._IdDocente = value;
					this.SendPropertyChanged("IdDocente");
					this.OnIdDocenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(30)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(30)")]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_n", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_n
		{
			get
			{
				return this._fecha_n;
			}
			set
			{
				if ((this._fecha_n != value))
				{
					this.Onfecha_nChanging(value);
					this.SendPropertyChanging();
					this._fecha_n = value;
					this.SendPropertyChanged("fecha_n");
					this.Onfecha_nChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genero", DbType="Char(1)")]
		public System.Nullable<char> genero
		{
			get
			{
				return this._genero;
			}
			set
			{
				if ((this._genero != value))
				{
					this.OngeneroChanging(value);
					this.SendPropertyChanging();
					this._genero = value;
					this.SendPropertyChanged("genero");
					this.OngeneroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int")]
		public System.Nullable<int> idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Docentes_Cursos", Storage="_Cursos", ThisKey="IdDocente", OtherKey="idDocente")]
		public EntitySet<Cursos> Cursos
		{
			get
			{
				return this._Cursos;
			}
			set
			{
				this._Cursos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Docentes", Storage="_Usuario", ThisKey="idUsuario", OtherKey="IdUsuario", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Docentes.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Docentes.Add(this);
						this._idUsuario = value.IdUsuario;
					}
					else
					{
						this._idUsuario = default(Nullable<int>);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Cursos(Cursos entity)
		{
			this.SendPropertyChanging();
			entity.Docentes = this;
		}
		
		private void detach_Cursos(Cursos entity)
		{
			this.SendPropertyChanging();
			entity.Docentes = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Notas")]
	public partial class Notas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdNota;
		
		private System.Nullable<decimal> _Nota;
		
		private string _Estado;
		
		private System.Nullable<int> _idCursoAlumno;
		
		private EntityRef<CursoAlumno> _CursoAlumno;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdNotaChanging(int value);
    partial void OnIdNotaChanged();
    partial void OnNotaChanging(System.Nullable<decimal> value);
    partial void OnNotaChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnidCursoAlumnoChanging(System.Nullable<int> value);
    partial void OnidCursoAlumnoChanged();
    #endregion
		
		public Notas()
		{
			this._CursoAlumno = default(EntityRef<CursoAlumno>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNota", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdNota
		{
			get
			{
				return this._IdNota;
			}
			set
			{
				if ((this._IdNota != value))
				{
					this.OnIdNotaChanging(value);
					this.SendPropertyChanging();
					this._IdNota = value;
					this.SendPropertyChanged("IdNota");
					this.OnIdNotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nota", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Nota
		{
			get
			{
				return this._Nota;
			}
			set
			{
				if ((this._Nota != value))
				{
					this.OnNotaChanging(value);
					this.SendPropertyChanging();
					this._Nota = value;
					this.SendPropertyChanged("Nota");
					this.OnNotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(15)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCursoAlumno", DbType="Int")]
		public System.Nullable<int> idCursoAlumno
		{
			get
			{
				return this._idCursoAlumno;
			}
			set
			{
				if ((this._idCursoAlumno != value))
				{
					if (this._CursoAlumno.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidCursoAlumnoChanging(value);
					this.SendPropertyChanging();
					this._idCursoAlumno = value;
					this.SendPropertyChanged("idCursoAlumno");
					this.OnidCursoAlumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CursoAlumno_Notas", Storage="_CursoAlumno", ThisKey="idCursoAlumno", OtherKey="IdCurso_Alumno", IsForeignKey=true)]
		public CursoAlumno CursoAlumno
		{
			get
			{
				return this._CursoAlumno.Entity;
			}
			set
			{
				CursoAlumno previousValue = this._CursoAlumno.Entity;
				if (((previousValue != value) 
							|| (this._CursoAlumno.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CursoAlumno.Entity = null;
						previousValue.Notas.Remove(this);
					}
					this._CursoAlumno.Entity = value;
					if ((value != null))
					{
						value.Notas.Add(this);
						this._idCursoAlumno = value.IdCurso_Alumno;
					}
					else
					{
						this._idCursoAlumno = default(Nullable<int>);
					}
					this.SendPropertyChanged("CursoAlumno");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pagos")]
	public partial class Pagos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPago;
		
		private System.Nullable<int> _IdCurso;
		
		private System.Nullable<int> _IdAlumno;
		
		private EntityRef<Alumno> _Alumno;
		
		private EntityRef<Cursos> _Cursos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPagoChanging(int value);
    partial void OnIdPagoChanged();
    partial void OnIdCursoChanging(System.Nullable<int> value);
    partial void OnIdCursoChanged();
    partial void OnIdAlumnoChanging(System.Nullable<int> value);
    partial void OnIdAlumnoChanged();
    #endregion
		
		public Pagos()
		{
			this._Alumno = default(EntityRef<Alumno>);
			this._Cursos = default(EntityRef<Cursos>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPago", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdPago
		{
			get
			{
				return this._IdPago;
			}
			set
			{
				if ((this._IdPago != value))
				{
					this.OnIdPagoChanging(value);
					this.SendPropertyChanging();
					this._IdPago = value;
					this.SendPropertyChanged("IdPago");
					this.OnIdPagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCurso", DbType="Int")]
		public System.Nullable<int> IdCurso
		{
			get
			{
				return this._IdCurso;
			}
			set
			{
				if ((this._IdCurso != value))
				{
					if (this._Cursos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCursoChanging(value);
					this.SendPropertyChanging();
					this._IdCurso = value;
					this.SendPropertyChanged("IdCurso");
					this.OnIdCursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAlumno", DbType="Int")]
		public System.Nullable<int> IdAlumno
		{
			get
			{
				return this._IdAlumno;
			}
			set
			{
				if ((this._IdAlumno != value))
				{
					if (this._Alumno.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdAlumnoChanging(value);
					this.SendPropertyChanging();
					this._IdAlumno = value;
					this.SendPropertyChanged("IdAlumno");
					this.OnIdAlumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Alumno_Pagos", Storage="_Alumno", ThisKey="IdAlumno", OtherKey="IdAlumno", IsForeignKey=true)]
		public Alumno Alumno
		{
			get
			{
				return this._Alumno.Entity;
			}
			set
			{
				Alumno previousValue = this._Alumno.Entity;
				if (((previousValue != value) 
							|| (this._Alumno.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Alumno.Entity = null;
						previousValue.Pagos.Remove(this);
					}
					this._Alumno.Entity = value;
					if ((value != null))
					{
						value.Pagos.Add(this);
						this._IdAlumno = value.IdAlumno;
					}
					else
					{
						this._IdAlumno = default(Nullable<int>);
					}
					this.SendPropertyChanged("Alumno");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cursos_Pagos", Storage="_Cursos", ThisKey="IdCurso", OtherKey="IdCurso", IsForeignKey=true)]
		public Cursos Cursos
		{
			get
			{
				return this._Cursos.Entity;
			}
			set
			{
				Cursos previousValue = this._Cursos.Entity;
				if (((previousValue != value) 
							|| (this._Cursos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cursos.Entity = null;
						previousValue.Pagos.Remove(this);
					}
					this._Cursos.Entity = value;
					if ((value != null))
					{
						value.Pagos.Add(this);
						this._IdCurso = value.IdCurso;
					}
					else
					{
						this._IdCurso = default(Nullable<int>);
					}
					this.SendPropertyChanged("Cursos");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Temario")]
	public partial class Temario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdTema;
		
		private string _Tema;
		
		private string _Descripcion;
		
		private string _FotoTema;
		
		private System.Nullable<int> _IdCurso;
		
		private EntityRef<Cursos> _Cursos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTemaChanging(int value);
    partial void OnIdTemaChanged();
    partial void OnTemaChanging(string value);
    partial void OnTemaChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnFotoTemaChanging(string value);
    partial void OnFotoTemaChanged();
    partial void OnIdCursoChanging(System.Nullable<int> value);
    partial void OnIdCursoChanged();
    #endregion
		
		public Temario()
		{
			this._Cursos = default(EntityRef<Cursos>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTema", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdTema
		{
			get
			{
				return this._IdTema;
			}
			set
			{
				if ((this._IdTema != value))
				{
					this.OnIdTemaChanging(value);
					this.SendPropertyChanging();
					this._IdTema = value;
					this.SendPropertyChanged("IdTema");
					this.OnIdTemaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tema", DbType="VarChar(30)")]
		public string Tema
		{
			get
			{
				return this._Tema;
			}
			set
			{
				if ((this._Tema != value))
				{
					this.OnTemaChanging(value);
					this.SendPropertyChanging();
					this._Tema = value;
					this.SendPropertyChanged("Tema");
					this.OnTemaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(200)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FotoTema", DbType="VarChar(MAX)")]
		public string FotoTema
		{
			get
			{
				return this._FotoTema;
			}
			set
			{
				if ((this._FotoTema != value))
				{
					this.OnFotoTemaChanging(value);
					this.SendPropertyChanging();
					this._FotoTema = value;
					this.SendPropertyChanged("FotoTema");
					this.OnFotoTemaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCurso", DbType="Int")]
		public System.Nullable<int> IdCurso
		{
			get
			{
				return this._IdCurso;
			}
			set
			{
				if ((this._IdCurso != value))
				{
					if (this._Cursos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCursoChanging(value);
					this.SendPropertyChanging();
					this._IdCurso = value;
					this.SendPropertyChanged("IdCurso");
					this.OnIdCursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cursos_Temario", Storage="_Cursos", ThisKey="IdCurso", OtherKey="IdCurso", IsForeignKey=true)]
		public Cursos Cursos
		{
			get
			{
				return this._Cursos.Entity;
			}
			set
			{
				Cursos previousValue = this._Cursos.Entity;
				if (((previousValue != value) 
							|| (this._Cursos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cursos.Entity = null;
						previousValue.Temario.Remove(this);
					}
					this._Cursos.Entity = value;
					if ((value != null))
					{
						value.Temario.Add(this);
						this._IdCurso = value.IdCurso;
					}
					else
					{
						this._IdCurso = default(Nullable<int>);
					}
					this.SendPropertyChanged("Cursos");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdUsuario;
		
		private string _Usuario1;
		
		private string _correo;
		
		private string _contraseña;
		
		private System.Nullable<int> _tipo;
		
		private System.Nullable<int> _Activo;
		
		private EntitySet<compras> _compras;
		
		private EntitySet<Alumno> _Alumno;
		
		private EntitySet<Docentes> _Docentes;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdUsuarioChanging(int value);
    partial void OnIdUsuarioChanged();
    partial void OnUsuario1Changing(string value);
    partial void OnUsuario1Changed();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OncontraseñaChanging(string value);
    partial void OncontraseñaChanged();
    partial void OntipoChanging(System.Nullable<int> value);
    partial void OntipoChanged();
    partial void OnActivoChanging(System.Nullable<int> value);
    partial void OnActivoChanged();
    #endregion
		
		public Usuario()
		{
			this._compras = new EntitySet<compras>(new Action<compras>(this.attach_compras), new Action<compras>(this.detach_compras));
			this._Alumno = new EntitySet<Alumno>(new Action<Alumno>(this.attach_Alumno), new Action<Alumno>(this.detach_Alumno));
			this._Docentes = new EntitySet<Docentes>(new Action<Docentes>(this.attach_Docentes), new Action<Docentes>(this.detach_Docentes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Usuario", Storage="_Usuario1", DbType="VarChar(60)")]
		public string Usuario1
		{
			get
			{
				return this._Usuario1;
			}
			set
			{
				if ((this._Usuario1 != value))
				{
					this.OnUsuario1Changing(value);
					this.SendPropertyChanging();
					this._Usuario1 = value;
					this.SendPropertyChanged("Usuario1");
					this.OnUsuario1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(60)")]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contraseña", DbType="VarChar(30)")]
		public string contraseña
		{
			get
			{
				return this._contraseña;
			}
			set
			{
				if ((this._contraseña != value))
				{
					this.OncontraseñaChanging(value);
					this.SendPropertyChanging();
					this._contraseña = value;
					this.SendPropertyChanged("contraseña");
					this.OncontraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="Int")]
		public System.Nullable<int> tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Int")]
		public System.Nullable<int> Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this.OnActivoChanging(value);
					this.SendPropertyChanging();
					this._Activo = value;
					this.SendPropertyChanged("Activo");
					this.OnActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_compras", Storage="_compras", ThisKey="IdUsuario", OtherKey="IdUsuario")]
		public EntitySet<compras> compras
		{
			get
			{
				return this._compras;
			}
			set
			{
				this._compras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Alumno", Storage="_Alumno", ThisKey="IdUsuario", OtherKey="idUsuario")]
		public EntitySet<Alumno> Alumno
		{
			get
			{
				return this._Alumno;
			}
			set
			{
				this._Alumno.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Docentes", Storage="_Docentes", ThisKey="IdUsuario", OtherKey="idUsuario")]
		public EntitySet<Docentes> Docentes
		{
			get
			{
				return this._Docentes;
			}
			set
			{
				this._Docentes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_compras(compras entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_compras(compras entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_Alumno(Alumno entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Alumno(Alumno entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_Docentes(Docentes entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Docentes(Docentes entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Inscripciones_del_Curso")]
	public partial class Inscripciones_del_Curso
	{
		
		private string _Nombre_del_Alumno;
		
		private string _Apellido_del_Alumno;
		
		private string _Curso;
		
		public Inscripciones_del_Curso()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nombre del Alumno]", Storage="_Nombre_del_Alumno", DbType="VarChar(30)")]
		public string Nombre_del_Alumno
		{
			get
			{
				return this._Nombre_del_Alumno;
			}
			set
			{
				if ((this._Nombre_del_Alumno != value))
				{
					this._Nombre_del_Alumno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Apellido del Alumno]", Storage="_Apellido_del_Alumno", DbType="VarChar(30)")]
		public string Apellido_del_Alumno
		{
			get
			{
				return this._Apellido_del_Alumno;
			}
			set
			{
				if ((this._Apellido_del_Alumno != value))
				{
					this._Apellido_del_Alumno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Curso", DbType="VarChar(30)")]
		public string Curso
		{
			get
			{
				return this._Curso;
			}
			set
			{
				if ((this._Curso != value))
				{
					this._Curso = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViewAlumnos")]
	public partial class ViewAlumnos
	{
		
		private int _IdAlumno;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private System.Nullable<System.DateTime> _Fecha_de_Nacimiento;
		
		private System.Nullable<char> _Género;
		
		private string _Usuario;
		
		private string _Correo;
		
		private System.Nullable<int> _Tipo_Usuario;
		
		public ViewAlumnos()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAlumno", DbType="Int NOT NULL")]
		public int IdAlumno
		{
			get
			{
				return this._IdAlumno;
			}
			set
			{
				if ((this._IdAlumno != value))
				{
					this._IdAlumno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(30)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(30)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha de Nacimiento]", Storage="_Fecha_de_Nacimiento", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_de_Nacimiento
		{
			get
			{
				return this._Fecha_de_Nacimiento;
			}
			set
			{
				if ((this._Fecha_de_Nacimiento != value))
				{
					this._Fecha_de_Nacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Género", DbType="Char(1)")]
		public System.Nullable<char> Género
		{
			get
			{
				return this._Género;
			}
			set
			{
				if ((this._Género != value))
				{
					this._Género = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(60)")]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(60)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this._Correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tipo Usuario]", Storage="_Tipo_Usuario", DbType="Int")]
		public System.Nullable<int> Tipo_Usuario
		{
			get
			{
				return this._Tipo_Usuario;
			}
			set
			{
				if ((this._Tipo_Usuario != value))
				{
					this._Tipo_Usuario = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViewCurso")]
	public partial class ViewCurso
	{
		
		private int _IdCurso;
		
		private string _Nombre;
		
		private string _Descripción;
		
		private string _Recursos;
		
		private System.Nullable<decimal> _Costo;
		
		private string _Nombre_Docente;
		
		public ViewCurso()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCurso", DbType="Int NOT NULL")]
		public int IdCurso
		{
			get
			{
				return this._IdCurso;
			}
			set
			{
				if ((this._IdCurso != value))
				{
					this._IdCurso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(30)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripción", DbType="VarChar(200)")]
		public string Descripción
		{
			get
			{
				return this._Descripción;
			}
			set
			{
				if ((this._Descripción != value))
				{
					this._Descripción = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recursos", DbType="VarChar(30)")]
		public string Recursos
		{
			get
			{
				return this._Recursos;
			}
			set
			{
				if ((this._Recursos != value))
				{
					this._Recursos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Costo", DbType="Money")]
		public System.Nullable<decimal> Costo
		{
			get
			{
				return this._Costo;
			}
			set
			{
				if ((this._Costo != value))
				{
					this._Costo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nombre Docente]", Storage="_Nombre_Docente", DbType="VarChar(30)")]
		public string Nombre_Docente
		{
			get
			{
				return this._Nombre_Docente;
			}
			set
			{
				if ((this._Nombre_Docente != value))
				{
					this._Nombre_Docente = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViewDocentes")]
	public partial class ViewDocentes
	{
		
		private int _IdDocente;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private System.Nullable<System.DateTime> _Fecha_de_Nacimiento;
		
		private System.Nullable<char> _Género;
		
		private string _Usuario;
		
		private string _Correo;
		
		private System.Nullable<int> _Tipo_Usuario;
		
		public ViewDocentes()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDocente", DbType="Int NOT NULL")]
		public int IdDocente
		{
			get
			{
				return this._IdDocente;
			}
			set
			{
				if ((this._IdDocente != value))
				{
					this._IdDocente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(30)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(30)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha de Nacimiento]", Storage="_Fecha_de_Nacimiento", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_de_Nacimiento
		{
			get
			{
				return this._Fecha_de_Nacimiento;
			}
			set
			{
				if ((this._Fecha_de_Nacimiento != value))
				{
					this._Fecha_de_Nacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Género", DbType="Char(1)")]
		public System.Nullable<char> Género
		{
			get
			{
				return this._Género;
			}
			set
			{
				if ((this._Género != value))
				{
					this._Género = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(60)")]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(60)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this._Correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tipo Usuario]", Storage="_Tipo_Usuario", DbType="Int")]
		public System.Nullable<int> Tipo_Usuario
		{
			get
			{
				return this._Tipo_Usuario;
			}
			set
			{
				if ((this._Tipo_Usuario != value))
				{
					this._Tipo_Usuario = value;
				}
			}
		}
	}
	
	public partial class SP_ModificaAlumnoResult
	{
		
		private string _Mensaje;
		
		public SP_ModificaAlumnoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(31) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class SP_ModificaCursosResult
	{
		
		private string _Mensaje;
		
		public SP_ModificaCursosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(31) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class SP_ModificaDocenteResult
	{
		
		private string _Mensaje;
		
		public SP_ModificaDocenteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(31) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class SP_ModificaNotasResult
	{
		
		private string _Mensaje;
		
		public SP_ModificaNotasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(31) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class SP_ModificaTemariosResult
	{
		
		private string _Mensaje;
		
		public SP_ModificaTemariosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(31) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
	
	public partial class SP_ModificaUsuarioResult
	{
		
		private string _Mensaje;
		
		public SP_ModificaUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensaje", DbType="VarChar(31) NOT NULL", CanBeNull=false)]
		public string Mensaje
		{
			get
			{
				return this._Mensaje;
			}
			set
			{
				if ((this._Mensaje != value))
				{
					this._Mensaje = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
